MailsControlSystem/Models/Incoming.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace MailsControlSystem.Models
{
    public class Incoming
    {
        [Key]
        public int IncomingID { set; get; }       

        [Display(Name = "De:")]
        public int From { set; get; }

        public string IncomingDate { set; get; }
        public string IncomingTime { set; get; }

        [Display(Name = "Cantidad recibida:")]
        [Required(ErrorMessage = "Se requiere la cantidad recibida.")]
        public string Quanty { set; get; }

        [Display(Name = "Descripción de la correspondencia:")]
        public string Description { set; get; }       
        
        public int IncomingMail { set; get; }

        [Display(Name = "Observaciones en la Recepción")]
        public string Observations { set; get; }
        
        [ForeignKey("From")]
        public virtual UserAccount UserAccount { set; get; }
        
        public virtual Mail Mail { set; get; }
    }
}

MailsControlSystem/Controllers/IncomingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailsControlSystem.Models;
using MailsControlSystem.DAL;
using System.Net.Mail;
using MailsControlSystem.Models.MembershipProvider;

namespace MailsControlSystem.Controllers
{
    public class IncomingController : Controller
    {
        private MailDBContext db = new MailDBContext();
        private CustomRoleProvider provider = new CustomRoleProvider();
        //
        // GET: /Incoming/
         [Authorize(Roles = "Administrador, Recepción, Enlace")]
        public ViewResult Index(string currentFilter, string searchString)
        {
            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var outcoming = from o in db.Outcomings
                            select o;
            var incoming = from i in db.Incomings
                           select i;
            var mail = from m in db.Mails
                       select m;
            List<Outcoming> listOutcoming = new List<Outcoming>();
            foreach (var item in outcoming)
            {
                listOutcoming.Add(item);
            }
            List<Incoming> listIncoming = new List<Incoming>();
            foreach (var item in incoming)
            {
                listIncoming.Add(item);
            }
            List<Mail> listMail = new List<Mail>();
            foreach (var item in mail)
            {
                listMail.Add(item);
            }

            List<Outcoming> listOut = outcoming.ToList();
            List<Incoming> listIn = incoming.ToList();

            List<IOMailWrapperModel> list = new List<IOMailWrapperModel>();
            //Geting the current Login Account
            String currentUser = User.Identity.Name;
            for (int i = 0; i < listOutcoming.Count; i++)
            {
                IOMailWrapperModel model = new IOMailWrapperModel();

                model.outcoming = listOutcoming.ElementAt(i);
                model.incoming = listIncoming.ElementAt(i);
                model.mail = listMail.ElementAt(i);

                if (!provider.GetRoleByUser(currentUser).Equals("Administrador"))
                {
                    //adding only the same region that the login user
                    if (provider.GetRegionByUser(currentUser) == model.outcoming.City)
                    {
                        list.Add(model);
                    }
                }
                else
                {
                    list.Add(model);
                }
            }

            IEnumerable<IOMailWrapperModel> enumModel = list;

            if (!String.IsNullOrEmpty(searchString))
            {
                int value = int.Parse(searchString);
                enumModel = list.Where(u => u.mail.GuideNumber.Equals(value));
                //incoming = incoming.Where(i => i.Mail.GuideNumber.Equals(value));
            }
            return View(enumModel); //concat two list
        }

        //
        // GET: /Incoming/Details/5

        public ActionResult Details(int id)
        {
            Incoming incoming = db.Incomings.Find(id);
            Outcoming outcoming = db.Outcomings.Find(id);
            Mail mail = db.Mails.Find(id);
            IOMailWrapperModel model = new IOMailWrapperModel();
            model.outcoming = outcoming;
            model.incoming = incoming;
            model.mail = mail;
            return View(model);
        }

        //
        // GET: /Incoming/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Incoming/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Incoming/Edit/5

        public ActionResult Edit(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            Incoming incoming = db.Incomings.Find(id);
            Mail mail = db.Mails.Find(id);

            ViewBag.To = new SelectList(db.People, "PersonID", "FullName", outcoming.To);
            ViewBag.From = new SelectList(db.People, "PersonID", "FullName", incoming.From);
            ViewBag.MailStatus = new SelectList(db.LMStatus, "MailStatusID", "MailStatusDescription", mail.MailStatus);
            ViewBag.IncomingID = new SelectList(db.Mails, "MailID", "MailID", incoming.IncomingID);

            IOMailWrapperModel model = new IOMailWrapperModel();
            model.outcoming = outcoming;
            model.incoming = incoming;
            model.mail = mail;
            return View(model);
        }

        //
        // POST: /Incoming/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, IOMailWrapperModel model)
        {
            // TODO: Add update logic here         
            model.incoming.IncomingDate = DateTime.Now.ToShortDateString();
            model.incoming.IncomingTime = DateTime.Now.ToShortTimeString();
            try
            {
                if (ModelState.IsValid)
                {
                    Mail currentMail = new Mail()
                    {
                        MailID = model.outcoming.OutcomingID,
                        GuideNumber = model.mail.GuideNumber,
                        MailStatus = 2
                    };

                    model.outcoming.OutcomingMail = currentMail.MailID;
                    model.outcoming.Mail = currentMail;

                    model.incoming.IncomingMail = currentMail.MailID;
                    model.incoming.Mail = currentMail;
                    model.incoming.Description = model.outcoming.Description;
                    //model.outcoming.Observations = model.incoming.Observations;

                    model.mail = currentMail;

                    db.Entry(model.outcoming).State = EntityState.Modified;
                    db.Entry(model.incoming).State = EntityState.Modified;
                    db.Entry(model.mail).State = EntityState.Modified;
                    db.SaveChanges();

                    IOMailWrapperModel SendMail = new IOMailWrapperModel();
                    SendMail = model;

                    int from = model.incoming.From;
                    int to = model.outcoming.To;


                    //Sending the Email Notification
                    SendEmailNotification(from, to, SendMail);

                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "No se guardaron los cambios, Vuelva a intentarlo, si el problema persiste notifique al administrador del sistema.");
            }
            ViewBag.MailStatus = new SelectList(db.LMStatus, "MailStatusID", "MailStatusDescription", model.mail.MailStatus);
            return View();
        }

        private void SendEmailNotification(int from, int to, IOMailWrapperModel mailModel)
        {
            Person incoming = db.People.Find(from);
            Person outcoming = db.People.Find(to);

            //Componiendo el email en HTML
            string notificationFrom = "<p>Le notificamos que se registro la llegada y recepción de la siguiente correspondencia:</p>" +
                    "<table style='width:100%;' align='center' title='Detalle' border='1'>" +
                        "<tr>" +
                            "<td align='center'><strong>Nro de Guía</Strong></td>" +
                            "<td align='center'><strong>Remitente</Strong></td>" +
                            "<td align='center'><strong>Destinatario</Strong></td>" +
                            "<td align='center'><strong>Hora Recepción</Strong></td>" +
                            "<td align='center'><strong>Fecha Recepción</Strong></td>" +
                            "<td align='center'><strong>Descripción</Strong></td>" +
                            "<td align='center'><strong>Cant. Recibida</Strong></td>" +
                            "<td align='center'><strong>Destino</Strong></td>" +
                        "</tr>" +
                        "<tr>" +
                            "<td align='center'>" + mailModel.mail.GuideNumber + "</td>" +
                            "<td align='center'>" + incoming.FullName + "</td>" +
                            "<td align='center'>" + outcoming.FullName + "</td>" +
                            "<td align='center'>" + mailModel.incoming.IncomingTime + "</td>" +
                            "<td align='center'>" + mailModel.incoming.IncomingDate + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.Description + "</td>" +
                            "<td align='center'>" + mailModel.incoming.Quanty + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.City + "</td>" +
                        "</tr>" +
                    "</table>" +
                    "<p>NOTA: Correo electrónico de prueba</p>" +
                    "<p>Este correo electrónico fue generado por el Sistema de Control de Correspondencia y los datos indicados no son reales.</p>" +
                    "<p>Si usted duda de la procedencia de éste correo puede contactarse con Janeth Mendoza (Recepción) o Caleb Espinoza (Asistente IT)</p>" +
                    "<a href='www.compassionbo.com'>Sistema de Control de Correspondencia</a>" +
                    "<hr />";

            //Correo para el Remitente
            MailMessage emailFrom = new MailMessage(incoming.Email.Trim(), incoming.Email.Trim());

MailsControlSystem/Controllers/OutcomingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailsControlSystem.Models;
using MailsControlSystem.DAL;

namespace MailsControlSystem.Controllers
{
    public class OutcomingController : Controller
    {
        private MailDBContext db = new MailDBContext();

        //
        // GET: /Outcoming/

        public ViewResult Index(string currentFilter, string searchString)
        {          
            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var outcoming = from o in db.Outcomings
                            select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                int value = int.Parse(searchString);
                outcoming = outcoming.Where(u => u.Mail.GuideNumber.Equals(value));//.Contains(searchString.ToUpper()));
            }
            //var outcomings = db.Outcomings.Include(o => o.UserAccount).Include(o => o.Mail);
            return View(outcoming.ToList());
        }

        //
        // GET: /Outcoming/Details/5

        public ViewResult Details(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Create

        public ActionResult Create()
        {
            ViewBag.OutcomingMail = new SelectList(db.Mails, "MailID", "Mail");
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account");
            ViewBag.From = new SelectList(db.UsersAccounts, "UserAccountID", "Account");
            return View();
        }

        //
        // POST: /Outcoming/Create

        [HttpPost]
        public ActionResult Create(Outcoming outcoming, Mail mail)
        {
            if (ModelState.IsValid)
            {
                Mail currentMail = new Mail()
                {
                    MailID = outcoming.OutcomingID,
                    GuideNumber = mail.GuideNumber,
                    MailStatus = 1
                };
                outcoming.OutcomingMail = currentMail.MailID;
                outcoming.Mail = currentMail;
                db.Outcomings.Add(outcoming);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Edit/5

        public ActionResult Edit(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // POST: /Outcoming/Edit/5

        [HttpPost]
        public ActionResult Edit(Outcoming outcoming)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outcoming).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Delete/5

        public ActionResult Delete(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            return View(outcoming);
        }

        //
        // POST: /Outcoming/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            db.Outcomings.Remove(outcoming);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MailsControlSystem/Views/Incoming/Details.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel
@{
    ViewBag.Title = "Details";
}
<h2>
    Detalle</h2>
<fieldset>
    <legend>Recepción</legend>
    <div class="display-label">
        Remitente</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.incoming.UserAccount.Person.FullName)
    </div>
    <div class="display-label">
        Destinatario</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.UserAccount.Person.FullName)
    </div>
    <div class="display-label">
        Fecha Recepción</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.incoming.IncomingDate)
    </div>
    <div class="display-label">
        Hora de Recepción</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.incoming.IncomingTime)
    </div>
    <div class="display-label">
        Estado del Pedido</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mail.ListMailStatus.MailStatusDescription)
    </div>
    <div class="display-label">
        Cantidad</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Quanty)
    </div>
    <div class="display-label">
        Descripción</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Description)
    </div>
    <div class="display-label">
        Ciudad</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.City)
    </div>
    <div class="display-label">
        Observaciones</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Observations)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.outcoming.OutcomingID }) |
    @Html.ActionLink("Atrás", "Index", "Outcoming")
</p>

MailsControlSystem/Views/Incoming/Edit.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel
@{
    ViewBag.Title = "Edit";
}
<h2>
    Editar Recepción de Correspondencia</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Formulario</legend>
        @Html.HiddenFor(model => model.outcoming.OutcomingID)
        @Html.HiddenFor(model => model.incoming.IncomingID)
        @Html.HiddenFor(model => model.mail.MailID)
        @Html.HiddenFor(model => model.outcoming.Quanty)
        @Html.HiddenFor(model => model.outcoming.Observations)
        @Html.HiddenFor(model => model.outcoming.City)
        @Html.HiddenFor(model => model.outcoming.Description)
        @Html.HiddenFor(model => model.outcoming.SendDate)
        @Html.HiddenFor(model => model.outcoming.SendTime)
        @Html.HiddenFor(model => model.incoming.Description)
        @Html.HiddenFor(model => model.incoming.IncomingDate)
        @Html.HiddenFor(model => model.incoming.IncomingTime)
        @Html.HiddenFor(model => model.mail.GuideNumber)
        @Html.HiddenFor(model => model.incoming.From)
        @Html.HiddenFor(model => model.outcoming.To)
        @*@Html.HiddenFor(model => model.outcoming.UserAccount)
        @Html.HiddenFor(model => model.incoming.UserAccount)*@

        <div class="editor-label">
            @Html.LabelFor(model => model.incoming.Quanty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.incoming.Quanty)
            @Html.ValidationMessageFor(model => model.incoming.Quanty)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.incoming.Observations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.incoming.Observations)
            @Html.ValidationMessageFor(model => model.incoming.Observations)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Volver a la Lista", "Index", "Incoming")
</div>

MailsControlSystem/Views/Incoming/Index.cshtml
@model IEnumerable<MailsControlSystem.Models.IOMailWrapperModel>
@{
    ViewBag.Title = "Lista";
}
<h2>Lista de Recepción de Correspondencia</h2>
@using (Html.BeginForm())
{
    <p>
        Buscar por Nro de Guía: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) &nbsp;
        <input type="submit" value="Buscar" />
    </p>
}
<table>
    <tr>
        <th>
            Fecha Recepcíon
        </th>
        <th>
            Hora Recepcíon
        </th>
        <th>
            Guía
        </th>
        <th>
            Remitente
        </th>
        <th>
            Destinatario
        </th>
        <th>
            Descripción
        </th>
        <th>
            Obs. Envío
        </th>
        <th>
            Cant. Enviada
        </th>
        <th>
            Cant. Recibida
        </th>
        <th>
            Obs. Recepción
        </th>
        <th>
            Estado del Pedido
        </th>
        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.IncomingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.IncomingTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mail.GuideNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.UserAccount.Person.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.outcoming.UserAccount.Person.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.outcoming.Observations)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.outcoming.Quanty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.Quanty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.incoming.Observations)
            </td>
            <td>
                @Html.DisplayFor(model => item.mail.ListMailStatus.MailStatusDescription)
            </td>
            <td>
                @Html.ActionLink("Registrar Recepción", "Edit", new { id = item.incoming.IncomingID }) |
                @*@Html.ActionLink("Details", "Details", new { id = item.IncomingID }, null) |*@
                @*@Html.ActionLink("Borrar", "Delete", "IOMail", new { id = item.incoming.IncomingID }, null)*@
            </td>
            
        </tr>
    }
</table>