MailsControlSystem/Controllers/IOMailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailsControlSystem.Models;
using MailsControlSystem.Models.MembershipProvider;
using MailsControlSystem.DAL;
using System.Web.Helpers;
using System.Net.Mail;
using System.Web.Security;

namespace MailsControlSystem.Controllers
{
    public class IOMailController : Controller
    {
        private MailDBContext db = new MailDBContext();
        private CustomRoleProvider provider = new CustomRoleProvider();
        //
        // GET: /IOMail/

        //public ActionResult Index()
        //{    
        //    return View();
        //}
        [Authorize(Roles = "Administrador,Recepción, Enlace")]
        public ViewResult Index(string currentFilter, string searchString)
        {
            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var outcoming = from o in db.Outcomings
                            select o;
            var incoming = from i in db.Incomings 
                           select i;
            var mail = from m in db.Mails 
                       select m;
            List<Outcoming> listOutcoming = new List<Outcoming>();                 
            foreach (var item in outcoming)
            {                
                    listOutcoming.Add(item);
            }
            List<Incoming> listIncoming = new List<Incoming>();
            foreach (var item in incoming)
            {
                listIncoming.Add(item);
            }
            List<Mail> listMail = new List<Mail>();
            foreach (var item in mail)
            {
                listMail.Add(item);
            }            
         
            List<Outcoming> listOut = outcoming.ToList();
            List<Incoming> listIn = incoming.ToList();
            
            List<IOMailWrapperModel> list = new List<IOMailWrapperModel>();
            //Geting the current Login Account
            String currentUser = User.Identity.Name;                   
            for (int i  = 0; i  < listOutcoming.Count; i ++)
            {
                IOMailWrapperModel model = new IOMailWrapperModel();              

                model.outcoming = listOutcoming.ElementAt(i);
                model.incoming = listIncoming.ElementAt(i);
                model.mail = listMail.ElementAt(i);

                if (!provider.GetRoleByUser(currentUser).Equals("Administrador"))
                {
                    //adding only the same region that the login user
                    if (provider.GetRegionByUser(currentUser) == model.outcoming.City)
                    {
                        //Cheking if the Outcoming have been created by the current User
                        if(model.outcoming.Sender != null && model.outcoming.Sender.Equals(currentUser))
                            list.Add(model);
                    }
                }
                else 
                {
                    list.Add(model);        
                }                   
            }

            IEnumerable<IOMailWrapperModel> enumModel = list;

            if (!String.IsNullOrEmpty(searchString))
            {
                int value = int.Parse(searchString);
                enumModel = list.Where(u => u.mail.GuideNumber.Equals(value));          
            }
            return View(enumModel); 
        }

        //
        // GET: /IOMail/Details/5

        public ActionResult Details(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            Incoming incoming = db.Incomings.Find(id);
            IOMailWrapperModel model = new IOMailWrapperModel();
            model.outcoming = outcoming;
            model.incoming = incoming;
            return View(model);
        }
        //
        // GET: /IOMail/Create

        public ActionResult Create()
        {      
            ViewBag.To = new SelectList(db.People, "PersonID", "FullName");
            ViewBag.From = new SelectList(db.People, "PersonID", "FullName");
            return View();
        }

        //
        // POST: /IOMail/Create

        [HttpPost,AcceptVerbs(HttpVerbs.Post) ] 
        public ActionResult Create(IOMailWrapperModel mailModel)
        {
            // Sorry Caleb,
            // by some reason I cannot get the value directly  from the DropDownList, in that case I'd to populate from the request
            int from = int.Parse(Request.Form["From"]); 
            int to = int.Parse(Request.Form["To"]);

            //Adding the Accunt that was created the Outcoming
            string sender = User.Identity.Name;

            mailModel.outcoming.To = to;
            mailModel.incoming.From = from;

            if (ModelState.IsValid)
            {
                Mail currentMail = new Mail()
                {
                    MailID = mailModel.outcoming.OutcomingID,
                    GuideNumber = mailModel.mail.GuideNumber,
                    MailStatus = 1
                };

                mailModel.outcoming.OutcomingMail = currentMail.MailID;
                mailModel.outcoming.Mail = currentMail;
                mailModel.outcoming.Sender = sender;

                mailModel.incoming.IncomingMail = currentMail.MailID;
                mailModel.incoming.Mail = currentMail;
                mailModel.incoming.Description = mailModel.outcoming.Description;
                mailModel.incoming.Quanty = "0";
              
                db.Outcomings.Add(mailModel.outcoming);
                db.Incomings.Add(mailModel.incoming);                
                db.SaveChanges();

                IOMailWrapperModel SendMail = new IOMailWrapperModel();
                SendMail = mailModel;

                //Sending the Email Notification
                SendEmailNotification(from, to, SendMail);
                return RedirectToAction("Index");
            }
            return View(mailModel);
        }

        /// <summary>
        /// Send a Email Notification to Senter and Receiver
        /// </summary>
        /// <param name="from">Id for Senter</param>
        /// <param name="to">Id for Reciever</param>
        private void SendEmailNotification(int from, int to, IOMailWrapperModel mailModel)
        {
            Person incoming = db.People.Find(from);
            Person outcoming = db.People.Find(to);

            //Componiendo el email en HTML
            string notificationFrom = "<p>Le notificamos que se registro el envío de correspondencia con el siguiente detalle:</p>" +
                    "<table style='width:100%;' align='center' title='Detalle' border='1'>" +
                        "<tr>" +
                            "<td align='center'><strong>Nro de Guía</Strong></td>" +
                            "<td align='center'><strong>Remitente</Strong></td>" +
                            "<td align='center'><strong>Destinatario</Strong></td>" +
                            "<td align='center'><strong>Hora de Envío</Strong></td>" +
                            "<td align='center'><strong>Fecha de Envío</Strong></td>" +
                            "<td align='center'><strong>Descripción</Strong></td>" +
                            "<td align='center'><strong>Cantidad</Strong></td>" +
                            "<td align='center'><strong>Destino</Strong></td>" +
                        "</tr>" +
                        "<tr>" +
                            "<td align='center'>" + mailModel.mail.GuideNumber + "</td>" +
                            "<td align='center'>" + incoming.FullName + "</td>" +
                            "<td align='center'>" + outcoming.FullName + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.SendTime + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.SendDate + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.Description + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.Quanty + "</td>" +
                            "<td align='center'>" + mailModel.outcoming.City + "</td>" +
                        "</tr>" +
                    "</table>" +
                    "<p>NOTA: Correo electrónico de prueba</p>" +
                    "<p>Este correo electrónico fue generado por el Sistema de Control de Correspondencia y los datos indicados no son reales.</p>" +
                    "<p>Si usted duda de la procedencia de éste correo puede contactarse con Janeth Mendoza (Recepción) o Caleb Espinoza (Asistente IT)</p>"+
                    "<a href='www.compassionbo.com'>Sistema de Control de Correspondencia</a>" +
                    "<hr />";
            
            //Correo para el Remitente
            MailMessage emailFrom = new MailMessage(incoming.Email.Trim(), incoming.Email.Trim());
            emailFrom.Subject = "Notificación de Envío de Correspondencia - Nro. Guía: " + mailModel.mail.GuideNumber;
            emailFrom.Body = "<p>Saludos " + incoming.FullName + ": </p>" + notificationFrom;
            emailFrom.IsBodyHtml = true;

            //Correo para el Destinatario
            MailMessage emailTo = new MailMessage(outcoming.Email.Trim(), outcoming.Email.Trim());
            emailTo.Subject = "Notificación de Envío de Correspondencia - Nro. Guía: " + mailModel.mail.GuideNumber;
            emailTo.Body = "<p>Saludos " + outcoming.FullName + ": </p>" + notificationFrom;
            emailTo.IsBodyHtml = true;

            SmtpClient notification = new SmtpClient("smtp.myopera.com", 587);
            notification.Credentials = new System.Net.NetworkCredential("compassionbo@myopera.com", "compassionbo");
            notification.EnableSsl = true;

            try
            {
                notification.Send(emailFrom);
                notification.Send(emailTo);

MailsControlSystem/Controllers/OutcomingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailsControlSystem.Models;
using MailsControlSystem.DAL;

namespace MailsControlSystem.Controllers
{
    public class OutcomingController : Controller
    {
        private MailDBContext db = new MailDBContext();

        //
        // GET: /Outcoming/

        public ViewResult Index(string currentFilter, string searchString)
        {          
            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var outcoming = from o in db.Outcomings
                            select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                int value = int.Parse(searchString);
                outcoming = outcoming.Where(u => u.Mail.GuideNumber.Equals(value));//.Contains(searchString.ToUpper()));
            }
            //var outcomings = db.Outcomings.Include(o => o.UserAccount).Include(o => o.Mail);
            return View(outcoming.ToList());
        }

        //
        // GET: /Outcoming/Details/5

        public ViewResult Details(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Create

        public ActionResult Create()
        {
            ViewBag.OutcomingMail = new SelectList(db.Mails, "MailID", "Mail");
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account");
            ViewBag.From = new SelectList(db.UsersAccounts, "UserAccountID", "Account");
            return View();
        }

        //
        // POST: /Outcoming/Create

        [HttpPost]
        public ActionResult Create(Outcoming outcoming, Mail mail)
        {
            if (ModelState.IsValid)
            {
                Mail currentMail = new Mail()
                {
                    MailID = outcoming.OutcomingID,
                    GuideNumber = mail.GuideNumber,
                    MailStatus = 1
                };
                outcoming.OutcomingMail = currentMail.MailID;
                outcoming.Mail = currentMail;
                db.Outcomings.Add(outcoming);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Edit/5

        public ActionResult Edit(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // POST: /Outcoming/Edit/5

        [HttpPost]
        public ActionResult Edit(Outcoming outcoming)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outcoming).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.To = new SelectList(db.UsersAccounts, "UserAccountID", "Account", outcoming.To);
            ViewBag.OutcomingID = new SelectList(db.Mails, "MailID", "MailID", outcoming.OutcomingID);
            return View(outcoming);
        }

        //
        // GET: /Outcoming/Delete/5

        public ActionResult Delete(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            return View(outcoming);
        }

        //
        // POST: /Outcoming/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Outcoming outcoming = db.Outcomings.Find(id);
            db.Outcomings.Remove(outcoming);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MailsControlSystem/Views/IOMail/Create.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel
@{
    ViewBag.Title = "Create";
}
<h2>Añadir Envío de Correspondencia</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Formulario de Envio</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.mail.GuideNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.mail.GuideNumber)
            @Html.ValidationMessageFor(model => model.mail.GuideNumber)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.incoming.From)
        </div>
        <div class="editor-field">
            @Html.DropDownList("From", "-Remitente-")
            @Html.ValidationMessageFor(model => model.incoming.From)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.To)
        </div>
        <div class="editor-field">
            @Html.DropDownList("To", "-Destinatario-")
            @Html.ValidationMessageFor(model => model.outcoming.To)
        </div>
        @Html.HiddenFor(model => model.outcoming.SendDate, new { Value = DateTime.Now.ToShortDateString() })
        @Html.HiddenFor(model => model.outcoming.SendTime, new { Value = DateTime.Now.ToShortTimeString() })

        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Quanty)
        </div>
        
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Quanty)
            @Html.ValidationMessageFor(model => model.outcoming.Quanty)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Description)
        </div>
        
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Description)
            @Html.ValidationMessageFor(model => model.outcoming.Description)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.City)
        </div>
        
        <div class="editor-field">
            @Html.DropDownListFor(model => model.outcoming.City, new[] {
                new SelectListItem() {Text = "Cochabamba", Value = "Cochabamba"},
                new SelectListItem() {Text = "Santa Cruz", Value = "Santa Cruz"},
                new SelectListItem() {Text = "La Paz", Value = "La Paz"},
                new SelectListItem() {Text = "Oruro", Value = "Oruro"},
                new SelectListItem() {Text = "Sucre", Value = "Sucre"},
                new SelectListItem() {Text = "Potosí", Value = "Potosí"}                                
                    }, "--Ciudad--")
            @Html.ValidationMessageFor(model => model.outcoming.City)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Observations)
        </div>
        
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Observations)
            @Html.ValidationMessageFor(model => model.outcoming.Observations)
        </div>
        <p>
            <input type="submit" value="Añadir" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Volver a la Lista", "Index", "IOMail")
</div>

MailsControlSystem/Views/IOMail/Delete.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Los datos eliminados afectarán el registro de Envíos y Recepciones</legend>
</fieldset>

    @Html.HiddenFor(model => model.outcoming.OutcomingID)
        @Html.HiddenFor(model => model.incoming.IncomingID)
        @Html.HiddenFor(model => Model.mail.MailID)
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Borrar" /> |
        @Html.ActionLink("Volver a la Lista", "Index","IOMail")
    </p>
}

MailsControlSystem/Views/IOMail/Details.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalle</h2>

<fieldset>
    <legend>Envío</legend>
    <div class="display-label">
        Remitente</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.incoming.UserAccount.Person.FullName)
    </div>
    <div class="display-label">
        Destinatario</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.UserAccount.Person.FullName)
    </div>
    <div class="display-label">
        Fecha Envío</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.SendDate)
    </div>
    <div class="display-label">
        Hora de Envío</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.SendTime)
    </div>
    <div class="display-label">
        Cantidad</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Quanty)
    </div>
    <div class="display-label">
        Descripción</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Description)
    </div>
    <div class="display-label">
        Ciudad</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.City)
    </div>
    <div class="display-label">
        Observaciones</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.outcoming.Observations)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", "IOMail", new { id = Model.outcoming.OutcomingID }, null) |
    @Html.ActionLink("Atrás", "Index", "Outcoming")
</p>

MailsControlSystem/Views/IOMail/Edit.cshtml
@model MailsControlSystem.Models.IOMailWrapperModel
@{
    ViewBag.Title = "Edit";
}
<h2>Editar Correspondencia</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Editar Correspondencia Enviada</legend>
        @Html.HiddenFor(model => model.outcoming.OutcomingID)
        @Html.HiddenFor(model => model.incoming.IncomingID)
        @Html.HiddenFor(model => Model.mail.MailID)
        @Html.HiddenFor(model => model.incoming.Quanty)
        <div class="editor-label">
            @Html.LabelFor(model => model.mail.GuideNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.mail.GuideNumber)
            @Html.ValidationMessageFor(model => model.outcoming.Mail.GuideNumber)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.incoming.From, "Remitente")
        </div>
        <div class="editor-field">
            @Html.DropDownList("From", String.Empty)
            @Html.ValidationMessageFor(model => model.incoming.From)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.To, "Destinatario")
        </div>
        <div class="editor-field">
            @Html.DropDownList("To", String.Empty)
            @Html.ValidationMessageFor(model => model.outcoming.To)
        </div>
            @Html.HiddenFor(model => model.outcoming.SendDate)
            @Html.HiddenFor(model => model.outcoming.SendTime)

        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Quanty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Quanty)
            @Html.ValidationMessageFor(model => model.outcoming.Quanty)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Description)
            @Html.ValidationMessageFor(model => model.outcoming.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.City)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.outcoming.City, new[] {
                new SelectListItem() {Text = "Cochabamba", Value = "Cochabamba"},
                new SelectListItem() {Text = "Santa Cruz", Value = "Santa Cruz"},
                new SelectListItem() {Text = "La Paz", Value = "La Paz"},
                new SelectListItem() {Text = "Oruro", Value = "Oruro"},
                new SelectListItem() {Text = "Sucre", Value = "Sucre"},
                new SelectListItem() {Text = "Potosí", Value = "Potosí"}                                
                    })
            @Html.ValidationMessageFor(model => model.outcoming.City)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.outcoming.Observations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.outcoming.Observations)
            @Html.ValidationMessageFor(model => model.outcoming.Observations)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Volver a la Lista", "Index", "IOMail")
</div>

MailsControlSystem/Views/IOMail/Index.cshtml
@model IEnumerable<MailsControlSystem.Models.IOMailWrapperModel>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista de Envíos</h2>

<p>
    @Html.ActionLink("Añadir Nuevo", "Create","IOMail")
</p>

@using (Html.BeginForm())
{
    <p>
        Buscar por Nro de Guía: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) &nbsp;
        <input type="submit" value="Buscar" />
    </p>
}

<table>
    <tr> 
        <th>
            Fecha de Envío
        </th>
        <th>
            Hora de Envío
        </th> 
        <th>
            Guía
        </th> 
        <th>
            Remitente
        </th>   
        <th>
            Destinatario
        </th>
        <th>
            Cant. Enviada
        </th>
        <th>
            Descripción
        </th>       
        <th>
            Destino
        </th>
        <th>
            Observaciones
        </th>   
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.SendDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.SendTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.mail.GuideNumber)
        </td>
        <td>
        @Html.DisplayFor(modelItem => item.incoming.UserAccount.Person.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.UserAccount.Person.FullName)
        </td>     
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.Quanty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.Description)
        </td>      
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.outcoming.Observations)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", "IOMail", new { id = item.outcoming.OutcomingID }, null) |
            @*@Html.ActionLink("Details", "Details", "IOMail",new { id=item.OutcomingID }, null) |*@
            @Html.ActionLink("Borrar", "Delete", "IOMail", new { id = item.outcoming.OutcomingID }, null)
        </td>
    </tr>
}
</table>